spring:

  datasource:
    url: jdbc:mysql://localhost:3306/practice?enabledTLSProtocols=TLSv1.2
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
        show_sql: true